project:
  type: website

website:
  title: "Kearney Data Science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/davidrkearney
      - icon: linkedin
        href: https://www.linkedin.com/in/davidrkearney/
format:
  html:
    theme: cosmo
    css: styles.css



